### ISSUE TITLE
Hello, little wrong there :)

### ISSUE THREAD

**Issue by razvandamian** [VeguiIzumi/NezumiYuiV.2#2]
Hello, you copy pasted the resume command from the music category same as skip command, and the serverlist command the back button doesn't work :), nice work

**Comment by VeguiIzumi** [comment]
Oh nooo, my bad, but thank you for reminding me, resume and skip is now functional as their function lol, about the server list command, I tried and its work, if u want the back button not deleting the embed, you can remove this :
if(i0 < 0){
   return msg.delete();
}
   if(!i0 || !i1){
      return msg.delete();
}

**Comment by razvandamian** [comment]
ok, thanks
