### ISSUE TITLE
Search command not working

### ISSUE THREAD

**Issue by razvandamian** [VeguiIzumi/NezumiYuiV.2#4]
Hello, i have a trouble with search command, i get an error when i want to play something
![image](https://user-images.githubusercontent.com/67657296/92533818-f07df400-f23b-11ea-9072-9de4ca3b7e97.png)

**Comment by VeguiIzumi** [comment]
Hello, can you check again ur ytb key? this problem may come because of your Ytb key, and again, I just tried it, and it works fine

**Comment by razvandamian** [comment]
yes, thanks my bad
