### ISSUE TITLE
A command where upvote on top.gg is needed to use.

### ISSUE THREAD

**Issue by BeeBuzz420** [VeguiIzumi/NezumiYuiV.2#8]
It would be cool if you add a feature where a user needs to upvote on top.gg to use that command.

Example:
When using volume command in music if you didn't vote for the bot on TOPGG it sends an error and if you voted in the last 12 hours the user can be able to use it.

**Comment by VeguiIzumi** [comment]
Oh ya, I know what you mean it is like premium commands, right? I'll keep in mind, thanks for your suggestion
